// base action type
const BASE = 'REQUEST_FETCH';

export const
  FETCH_ENTITY = `${BASE}_ENTITY`,
  FETCH_ENTITY_START = `${FETCH_ENTITY}_START`,
  FETCH_ENTITY_STOP = `${FETCH_ENTITY}_STOP`,
  ENTITY_FETCHED = `${FETCH_ENTITY}_SUCCESS`,
  ENTITY_FETCH_FAILED = `${FETCH_ENTITY}_FAILURE`
;

