// base action type
const BASE = 'REQUEST_FETCH';

export const
  FETCH_ENTITIES = `${BASE}_ENTITIES`,
  FETCH_ENTITIES_START = `${FETCH_ENTITIES}_START`,
  FETCH_ENTITIES_STOP = `${FETCH_ENTITIES}_STOP`,
  ENTITIES_FETCHED = `${FETCH_ENTITIES}SUCCESS`,
  ENTITIES_FETCH_FAILED = `${FETCH_ENTITIES}_FAILURE`
;

